# Generated by Django 6.0.3 on 2026-06-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewslot',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Provide a Google Meet, Zoom, or Teams link for this session.'),
        ),
    ]
